project_id = "slmwoczmrplhypurkgvx"

[api]
enabled = true
schemas = ["public", "storage"]

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]

[realtime]
enabled = true

[functions.rupkas-payment-proof]
verify_jwt = true
