import { useEffect, useState } from 'react';
import { confirmProPayment, getDeveloperOverview, getPaymentProofUrl, rejectProPayment, replySupportCaseAsDeveloper, type DeveloperOverview } from './commercial';

function DIcon({name}:{name:string}){return <span className="material-symbols-rounded" aria-hidden="true">{name}</span>}

export default function DeveloperConsole(){
  const [data,setData]=useState<DeveloperOverview|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState<Record<string,string>>({}),[reply,setReply]=useState<Record<string,string>>({});
  async function viewProof(orderId:string){setBusy(true);try{const result=await getPaymentProofUrl(orderId);window.open(result.signed_url,'_blank','noopener,noreferrer')}catch(e:any){setNotice(e?.message||'Bukti pembayaran tidak tersedia')}finally{setBusy(false)}}
  async function load(){setBusy(true);try{setData(await getDeveloperOverview());setNotice('')}catch(e:any){setNotice(e?.message||'Developer access denied')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  async function confirm(orderId:string){setBusy(true);try{await confirmProPayment(orderId);await load()}catch(e:any){setNotice(e?.message||'Gagal mengonfirmasi pembayaran')}finally{setBusy(false)}}
  async function reject(orderId:string){setBusy(true);try{await rejectProPayment(orderId,reason[orderId]);await load()}catch(e:any){setNotice(e?.message||'Gagal menolak pembayaran')}finally{setBusy(false)}}
  async function sendReply(caseId:string){const body=(reply[caseId]||'').trim();if(!body)return;setBusy(true);try{await replySupportCaseAsDeveloper(caseId,body);setReply({...reply,[caseId]:''});await load()}catch(e:any){setNotice(e?.message||'Gagal membalas support')}finally{setBusy(false)}}
  return <main className="developer-console"><section className="developer-shell"><header className="developer-header"><div><span className="eyebrow">RUPKAS CONTROL PLANE</span><h1>Developer Console</h1><p className="muted">Operational metadata only. Financial contents of user spaces are not exposed here.</p></div><button className="ghost" disabled={busy} onClick={()=>void load()}><DIcon name="refresh"/>Refresh</button></header>{notice&&<div className="notice">{notice}</div>}{!data?<section className="panel"><div className="empty">Memuat control plane…</div></section>:<><section className="developer-stats">{Object.entries(data.counts).map(([key,value])=><div className="panel developer-stat" key={key}><span>{key.replaceAll('_',' ')}</span><strong>{String(value)}</strong></div>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">ORDERS</span><h2>Payment Queue</h2></div></div>{data.orders.length?data.orders.map(order=><div className="developer-row" key={String(order.id)}><div><strong>{String(order.public_account_id||order.account_name||order.account_id)}</strong><span>{String(order.product_name_snapshot||order.plan_code)} · Rp{Number(order.amount_idr||0).toLocaleString('id-ID')} · {String(order.status)}</span><small>{String(order.payment_status||'')}</small></div><div className="developer-actions">{['PAID','REJECTED','CANCELLED','REFUNDED'].includes(String(order.status))?<span className="muted">{String(order.status)}</span>:<><button className="ghost" disabled={busy} onClick={()=>void viewProof(String(order.id))}><DIcon name="visibility"/>Proof</button><button className="primary" disabled={busy} onClick={()=>void confirm(String(order.id))}><DIcon name="check_circle"/>Confirm</button><div className="developer-reject"><input placeholder="Alasan penolakan" value={reason[String(order.id)]||''} onChange={e=>setReason({...reason,[String(order.id)]:e.target.value})}/><button className="ghost" disabled={busy} onClick={()=>void reject(String(order.id))}>Reject</button></div></>}</div></div>):<div className="empty">Tidak ada order.</div>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">SUPPORT</span><h2>Open Cases</h2></div></div>{data.support.length?data.support.map(item=><div className="developer-case" key={String(item.id)}><div><strong>{String(item.case_type)} · {String(item.priority)}</strong><span>{String(item.public_account_id||item.account_name||item.account_id)} · {String(item.status)}</span></div><div className="developer-reply"><textarea rows={2} placeholder="Balas user…" value={reply[String(item.id)]||''} onChange={e=>setReply({...reply,[String(item.id)]:e.target.value})}/><button className="ghost" disabled={busy||!(reply[String(item.id)]||'').trim()} onClick={()=>void sendReply(String(item.id))}><DIcon name="send"/>Kirim</button></div></div>):<div className="empty">Tidak ada support case terbuka.</div>}</section></>}</section></main>
}
