import React from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

export const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

function App(){
 const [session,setSession]=React.useState<any>(null); const [email,setEmail]=React.useState(''); const [password,setPassword]=React.useState(''); const [loading,setLoading]=React.useState(true); const [error,setError]=React.useState('');
 React.useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 async function signIn(){setError('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else setSession(data.session)}
 async function signUp(){setError('');const {error}=await supabase.auth.signUp({email,password});if(error)setError(error.message);else setError('Cek email untuk verifikasi akun Rupkas.');}
 if(loading)return <main className="center">Memuat Rupkas…</main>;
 if(!session)return <main className="auth"><section><div className="logo">R</div><h1>Rupkas</h1><p>Rupiah Kas — keuangan yang sederhana dan aman.</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={signIn}>Masuk</button><button className="secondary" onClick={signUp}>Daftar akun</button>{error&&<small>{error}</small>}</section></main>;
 return <Dashboard email={session.user.email}/>;
}
function Dashboard({email}:{email:string}){const [summary,setSummary]=React.useState<any>(null);const [spaces,setSpaces]=React.useState<any[]>([]);const [space,setSpace]=React.useState('');const [amount,setAmount]=React.useState('');const [note,setNote]=React.useState('');const [cats,setCats]=React.useState<any[]>([]);const [cat,setCat]=React.useState('');const [type,setType]=React.useState<'income'|'expense'>('expense');const [msg,setMsg]=React.useState('');
 async function load(){const {data:m}=await supabase.from('space_members').select('space_id,spaces(id,name,type)').eq('status','active');const ss=(m||[]).map((x:any)=>x.spaces).filter(Boolean);setSpaces(ss);const s=space||ss[0]?.id;if(s&&!space)setSpace(s);if(s){const {data:c}=await supabase.from('categories').select('*').eq('space_id',s).eq('type',type).eq('is_active',true);setCats(c||[]);setCat(c?.[0]?.id||'');const d=new Date();d.setDate(1);const start=d.toISOString().slice(0,10);const {data}=await supabase.rpc('get_month_summary',{p_space_id:s,p_month_start:start});setSummary(data?.[0]||null)}}
 React.useEffect(()=>{load()},[space,type]);
 async function add(){setMsg('');if(!space||!cat||!amount)return;const {error}=await supabase.rpc('create_transaction',{p_space_id:space,p_type:type,p_amount:Number(amount),p_category_id:cat,p_transaction_date:new Date().toISOString().slice(0,10),p_note:note||null,p_client_operation_id:crypto.randomUUID()});if(error)setMsg(error.message);else{setAmount('');setNote('');setMsg('Transaksi tersimpan.');load()}}
 return <main className="app"><header><div><b>Rupkas</b><span>{email}</span></div><button className="secondary" onClick={()=>supabase.auth.signOut()}>Keluar</button></header><section className="space"><label>Space</label><select value={space} onChange={e=>setSpace(e.target.value)}>{spaces.map(s=><option key={s.id} value={s.id}>{s.name} · {s.type}</option>)}</select></section><section className="grid"><article><span>Pemasukan</span><strong>Rp {Number(summary?.income_total||0).toLocaleString('id-ID')}</strong></article><article><span>Pengeluaran</span><strong>Rp {Number(summary?.expense_total||0).toLocaleString('id-ID')}</strong></article><article><span>Arus kas</span><strong>Rp {Number(summary?.net_cashflow||0).toLocaleString('id-ID')}</strong></article></section><section className="card"><h2>Tambah transaksi</h2><div className="tabs"><button className={type==='expense'?'active':''} onClick={()=>setType('expense')}>Pengeluaran</button><button className={type==='income'?'active':''} onClick={()=>setType('income')}>Pemasukan</button></div><input type="number" placeholder="Jumlah (Rp)" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Catatan (opsional)" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={add}>Simpan transaksi</button>{msg&&<small>{msg}</small>}</section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
