const DB_NAME='rupkas-offline-v1';
const STORE='tx_queue';
type PendingTx={id:string,space_id:string,type:'income'|'expense',amount:number,category_id:string,transaction_date:string,transaction_time:string,note:string|null,client_operation_id:string,created_at:number,attempts:number};
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('space_id','space_id');s.createIndex('client_operation_id','client_operation_id',{unique:true});}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function enqueueTransaction(x:Omit<PendingTx,'id'|'created_at'|'attempts'>){const d=await openDb();const row:PendingTx={...x,id:crypto.randomUUID(),created_at:Date.now(),attempts:0};await new Promise<void>((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function pendingCount(spaceId?:string){const d=await openDb();return await new Promise<number>((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),s=tx.objectStore(STORE),req=spaceId?s.index('space_id').count(spaceId):s.count();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function rows(spaceId?:string){const d=await openDb();return await new Promise<PendingTx[]>((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),s=tx.objectStore(STORE),req=spaceId?s.index('space_id').getAll(spaceId):s.getAll();req.onsuccess=()=>resolve(req.result as PendingTx[]);req.onerror=()=>reject(req.error)})}
async function remove(id:string){const d=await openDb();await new Promise<void>((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function bump(id:string,attempts:number){const d=await openDb();await new Promise<void>((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite'),s=tx.objectStore(STORE),r=s.get(id);r.onsuccess=()=>{if(r.result){r.result.attempts=attempts;s.put(r.result)}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function flushTransactionQueue(client:any,spaceId?:string){if(!navigator.onLine)return{sent:0,failed:0,pending:await pendingCount(spaceId)};const list=await rows(spaceId);let sent=0,failed=0;for(const x of list){const {error}=await client.rpc('create_transaction',{p_space_id:x.space_id,p_type:x.type,p_amount:x.amount,p_category_id:x.category_id,p_transaction_date:x.transaction_date,p_transaction_time:x.transaction_time,p_source_text:null,p_note:x.note,p_client_operation_id:x.client_operation_id});if(error){failed++;await bump(x.id,x.attempts+1)}else{sent++;await remove(x.id)}}return{sent,failed,pending:await pendingCount(spaceId)}}