create type public.space_type as enum ('personal','family');
create type public.member_role as enum ('owner','member');
create type public.tx_type as enum ('income','expense');
create type public.tx_status as enum ('confirmed','voided');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text not null,timezone text not null default 'Asia/Jakarta',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.spaces(id uuid primary key default gen_random_uuid(),name text not null,type public.space_type not null,owner_user_id uuid not null references auth.users(id),status text not null default 'active',created_at timestamptz not null default now(),version int not null default 1);
create unique index spaces_one_personal on public.spaces(owner_user_id) where type='personal' and status='active';
create table public.space_members(id uuid primary key default gen_random_uuid(),space_id uuid not null references public.spaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role public.member_role not null,status text not null default 'active',joined_at timestamptz not null default now(),unique(space_id,user_id));
create table public.categories(id uuid primary key default gen_random_uuid(),space_id uuid not null references public.spaces(id) on delete cascade,type public.tx_type not null,name text not null,is_system boolean not null default false,is_active boolean not null default true,unique(space_id,type,name));
create table public.transactions(id uuid primary key default gen_random_uuid(),space_id uuid not null references public.spaces(id) on delete cascade,type public.tx_type not null,status public.tx_status not null default 'confirmed',amount numeric(18,2) not null check(amount>0),currency_code text not null default 'IDR',category_id uuid not null references public.categories(id),transaction_date date not null,transaction_time time,note text,created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),version int not null default 1,client_operation_id uuid unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.budgets(id uuid primary key default gen_random_uuid(),space_id uuid not null references public.spaces(id) on delete cascade,period_start date not null,period_end date not null,limit_amount numeric(18,2) not null check(limit_amount>0),warning_percent numeric(5,2) default 80,unique(space_id,period_start,period_end));
create table public.savings_goals(id uuid primary key default gen_random_uuid(),space_id uuid not null references public.spaces(id) on delete cascade,name text not null,target_amount numeric(18,2) not null check(target_amount>0),target_date date,status text not null default 'active',created_by uuid not null references auth.users(id),created_at timestamptz not null default now());

create or replace function private.is_member(p_space uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.space_members where space_id=p_space and user_id=(select auth.uid()) and status='active') $$;
grant execute on function private.is_member(uuid) to authenticated;

alter table public.profiles enable row level security; alter table public.spaces enable row level security; alter table public.space_members enable row level security; alter table public.categories enable row level security; alter table public.transactions enable row level security; alter table public.budgets enable row level security; alter table public.savings_goals enable row level security;
create policy profile_self on public.profiles for all to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy spaces_member on public.spaces for select to authenticated using(private.is_member(id));
create policy members_member on public.space_members for select to authenticated using(private.is_member(space_id));
create policy categories_member on public.categories for select to authenticated using(private.is_member(space_id));
create policy tx_member on public.transactions for select to authenticated using(private.is_member(space_id));
create policy budgets_member on public.budgets for select to authenticated using(private.is_member(space_id));
create policy savings_member on public.savings_goals for select to authenticated using(private.is_member(space_id));

create or replace function public.create_transaction(p_space_id uuid,p_type public.tx_type,p_amount numeric,p_category_id uuid,p_transaction_date date,p_transaction_time time default null,p_note text default null,p_client_operation_id uuid default null) returns public.transactions language plpgsql security invoker set search_path=public,private as $$ declare v public.transactions; begin if not private.is_member(p_space_id) then raise exception 'FORBIDDEN'; end if; if p_client_operation_id is not null then select * into v from public.transactions where client_operation_id=p_client_operation_id; if found then return v; end if; end if; insert into public.transactions(space_id,type,amount,category_id,transaction_date,transaction_time,note,created_by,updated_by,client_operation_id) values(p_space_id,p_type,p_amount,p_category_id,p_transaction_date,p_transaction_time,p_note,(select auth.uid()),(select auth.uid()),p_client_operation_id) returning * into v; return v; end; $$;
grant execute on function public.create_transaction(uuid,public.tx_type,numeric,uuid,date,time,text,uuid) to authenticated;

create or replace function public.get_month_summary(p_space_id uuid,p_month_start date) returns table(income_total numeric,expense_total numeric,net_cashflow numeric,budget_limit numeric,budget_actual numeric,budget_utilization numeric) language sql security invoker set search_path=public,private as $$ with tx as(select coalesce(sum(amount) filter(where type='income' and status='confirmed'),0) income_total,coalesce(sum(amount) filter(where type='expense' and status='confirmed'),0) expense_total from public.transactions where space_id=p_space_id and transaction_date>=p_month_start and transaction_date<(p_month_start+interval '1 month')),b as(select coalesce((select limit_amount from public.budgets where space_id=p_space_id and p_month_start between period_start and period_end limit 1),0) budget_limit) select income_total,expense_total,income_total-expense_total,budget_limit,expense_total,case when budget_limit>0 then round(expense_total/budget_limit*100,2) else 0 end from tx cross join b $$;
grant execute on function public.get_month_summary(uuid,date) to authenticated;
